---
- name: stop keepalived service
  systemd:
    state: stopped
    name: keepalived
- name: remove keepalived package
  apt:
      name: ['keepalived']
      state: absent
      autoremove: yes
      purge: yes
- name: remove config from server
  file:
    path: "/etc/keepalived/keepalived.conf"
    state: absent